### PR TITLE
Update init.sh

### PR DESCRIPTION
**Pull request by KostyaSha**
This change is [Reviewable](https://reviewable.io/reviews/kostyasha/yet-another-docker-plugin/109)

### CODE REVIEW

**Comment by KostyaSha** [comment]
let's see whether integration test pass

**Comment by oleg-nenashev** [comment]
I'd rather just declare bash requirement in the invocation

**Comment by KostyaSha** [comment]
You know what? https://github.com/KostyaSha/yet-another-docker-plugin/pull/100/files#diff-61fa5bf6562d5796625d9d2be676c327R1

**Comment by oleg-nenashev** [comment]
:sadpanda:

**Pull request merged**
