### PR TITLE
Make sure that the config.ps1 is not locked before accessing it from the init.ps1 script.

### LINKED ISSUE #269: Container uses config.ps1 while it's still locked - Running the container fails with Exitcode 1
We use the `yad-plugin` to spin up on-demand build agents on a Windows Server 2019 Docker host. Sometimes the containers **fail when executing the `config.ps1` script**.

```
No config, sleeping for 1 second 
No config, sleeping for 1 second 
No config, sleeping for 1 second 
No config, sleeping for 1 second 
No config, sleeping for 1 second 
Found config file c:\\config.ps1 
 : The process cannot access the file 'C:\\config.ps1' because it is being used by another process.
At C:\\init.ps1:10 char:3 . \"$CONFIG\"
    + CategoryInfo          : ObjectNotFound: (:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

JENKINS_URL is not defined! Exiting.
```

To me this seems like the `powershell.exe` that performs the `init.ps1` script is interfering with the  `powershell.exe` from the `startCmd` which writes the `config.ps1` file. In short: **The config file is not written completely while the initialization already tries to execute it.**

https://github.com/KostyaSha/yet-another-docker-plugin/blob/e22e6fecec6340f7667d9f6d8f2646e7a5609ed2/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher.java#L199-L211

I think this could be fixed by checking whether the file is still locked in the `init.ps1` as suggested in this StackOverflow question: [Powershell: Check if a file is locked](https://stackoverflow.com/questions/24992681/powershell-check-if-a-file-is-locked).

We could introduce such a check somewhere here:

https://github.com/KostyaSha/yet-another-docker-plugin/blob/e22e6fecec6340f7667d9f6d8f2646e7a5609ed2/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.ps1#L3-L10

### PR DESCRIPTION
**Pull request by steffen-wilke**
This implements the suggestions I described in detail with Issue #269.
Once merged, this Closes #269

### CODE REVIEW

**Comment by KostyaSha** [comment]
Btw, for linux implementation there is suggestion to add additional timeout for the whole wait of this file to not have running containers on corner cases, would you like implement it for win?

**Comment by steffen-wilke** [comment]
Do you refer to #252? I can have a look at a windows implementation here. When I read this correctly you wanted to make this configurable from the UI?

**Comment by KostyaSha** [comment]
Like current settings passed to config, in script it's possible to insert timeout into waiting script

**Comment by steffen-wilke** [comment]
Sure. What value would you suggest here? As far as I understand this option wasn't added to the UI just yet. #252 adds a hardcoded 60 seconds timeout. 
So if you want me to I can add an option to the UI and then make sure that the timeout works on windows containers. I think we should maybe do this in a separate PR.

**Comment by KostyaSha** [comment]
I will merge current code, timeout could be added later.

**Pull request merged**
