### PR TITLE
WIP Add cloud-stats-plugin

### PR DESCRIPTION
**Pull request by KostyaSha**
#70

### CODE REVIEW

**Comment by KostyaSha** [comment]
@olivergondza for review

**Comment by KostyaSha** [comment]
screen shot 2016-09-14 at 22 44 18
I'm using unique ID's to identify templates and need `displayName`.

@olivergondza  Code looks like you moved part of things that you need in openstack plugin into stats objects.

Why `ProvisioningListener` is nested?

**Comment by KostyaSha** [comment]
Filled https://github.com/jenkinsci/cloud-stats-plugin/pull/2

**Comment by KostyaSha** [comment]
@olivergondza i can set computer name only after it was created, provisioning ID must be not final!

**Comment by KostyaSha** [comment]
Seems found, so a Slave, Node, will have provisionIds, byt name will be extracted only from latest?

**Comment by KostyaSha** [comment]
What cloud-stats will do if i use standard NodeProvisioner but don't need to track it's items because provisioning part produces PlannedNodes in different times than final listener see after `provision()` returns?

**Comment by KostyaSha** [comment]
One more thing, i restarted jenkins, slave removed, but stats-plugin still think that it running.

**Comment by KostyaSha** [comment]
Something doesn't work, i can't get "name" in UI even if i see it in xml storage. `rename` was definitely called.
System properties, sucks and must die. Allow configure in UI without restarting JVM.

**Comment by olivergondza** [comment]
> Why ProvisioningListener is nested?

To listen to provisioning activities started by `NodeProvisioner` and providing an API for plugins that provision nodes in different way.

> Code looks like you moved part of things that you need in openstack plugin into stats objects.

What exactly?

> I can set computer name only after it was created, provisioning ID must be not final!

`ProvisioningActivity#rename` should do it. In case your node name is not known in advance, do not specify it in `Id`.

**Comment by olivergondza** [comment]
> What cloud-stats will do if i use standard NodeProvisioner but don't need to track it's items because provisioning part produces PlannedNodes in different times than final listener see after provision() returns?

I do not understand the question/situation. In case you do not want to track some provisioning activity for some reason, provide `null` as `Id`.

> One more thing, i restarted jenkins, slave removed, but stats-plugin still think that it running.

[There is no reliable way to detect node was deleted](https://issues.jenkins-ci.org/browse/JENKINS-33780). Cloud stats have a periodic check to discover that until there is better API.

**Comment by olivergondza** [comment]
The diff looks good to me. Let me know if there is something that still does not work. For now, thanks for the feedback.

**Comment by KostyaSha** [comment]
It doesn't work, i also failed to trace what all this attachments call and do with this nested classes.

`provision` call returns list of plannednodes and every plannedNode must have it's own creation timings. I can't set Id to null because i set correct events, but standardListener do actions after. Plus name still doesn't work even if i called complete with rename, so there is bug somewhere  in cloud-stats.

**Comment by KostyaSha** [comment]
cloud-stats-plugin code looks like standard legacy jenkins code, i can't understand and fix naming, called phases, UI display info, so skipping it's integration. On other hand if somebody really needs to know such information there is metrics-plugin that allows attach timing metrics to builds and probably could be extended to support cloud information.

**Comment by KostyaSha** [comment]
Need somehow track launches from internal stuff (mostly for debug purposes) so temporary adding it back. If plugin will be good will keep.

**Pull request merged**
